print('         *         ')
print('        * *        ')
print('       * * *       ')
print('      * * * *      ')
print('     * * * * *     ')
print('    * *N*E*W* *    ')
print('   * *Y*E*A*R* *   ')
print('  * * * * * * * *  ')
print(' * * * * * * * * * ')
print('* * * * * * * * * *')
print('         **        ')
print('         **        ')